app/routes/web.php
<?php

use App\Http\Controllers\ListesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/home', function() {
    return view('home');
})->middleware(['auth'])->name('home');

Route::resource('/listes', ListesController::class)
    ->middleware(['auth']);
Route::post('/listes/import', [ListesController::class, 'import'])
    ->name('listes.import')
    ->middleware(['auth']);

Route::get('/admin', [\App\Http\Controllers\AdminController::class, 'index'])
    ->name('admin.index')
    ->middleware(['auth']);
Route::post('/admin', [\App\Http\Controllers\AdminController::class, 'store'])
    ->name('admin.store')
    ->middleware(['auth']);

Route::resource('/search', \App\Http\Controllers\SearchController::class)
    ->middleware(['auth']);

Route::resource('/items', \App\Http\Controllers\ItemsController::class)
    ->middleware(['auth']);

app/app/Models/Liste.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Liste extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'nom'];

    public function User(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function Items() {
        return $this->hasMany(Item::class);
    }
}

app/app/Http/Controllers/ListesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Liste;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ListesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Afficher les listes
        // - Mes listes
        // - Les listes publiques
        $mesListes = auth()->user()->listes()->with('user')->get();
        $pubListes = Liste::where('public', 1)->with('user')->get();
        $listes = $mesListes->merge($pubListes);

        return view('listes.index', [
            'listes' => $listes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Créer la liste
        $liste = new Liste();
        $liste->nom = $request->nomListe;
        $liste->public = ($request->listePublique === "1");
        $liste->User()->associate(auth()->user());
        $liste->save();

        // Rediriger
        return redirect()->route('listes.show', $liste);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Liste $liste)
    {
//        if (auth()->user()->user_id !== $liste->user_id) {
//            return abort(403, "Accès refusé");
//        }

        $items = $liste->items;
        return view('listes.show', [
            'liste' => $liste,
            'items' => $items
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Liste $liste)
    {
        $liste->delete();
        return redirect()->route('listes.index')
            ->with('message', 'La liste "' . $liste->nom . '" a été supprimée avec succès')
            ->with('couleur', 'success');
    }

    public function import(Request $request) {
        $fichierXml = $request->file('fichierXML');
        $xml = new \SimpleXMLElement($fichierXml->get(), LIBXML_NOENT);

        // Créer la liste
        $liste = new Liste();
        $liste->nom = (string) $xml->liste;
        $liste->public = false;
        $liste->User()->associate(auth()->user());
        $liste->save();

        // Ajouter les items
        foreach ($xml->items->item as $item) {
            $newItem = new Item();
            $newItem->nom = (string) $item;
            $newItem->quantite = (int) $item['qte'];
            $newItem->liste()->associate($liste);
            $newItem->save();
        }

        // Afficher la liste
        return back();
    }
}

app/resources/views/listes/index.blade.php
@extends('layouts.base')

@section('titre')
    Mes listes
@endsection

@section('actions')
    <!-- Créer une liste -->
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalNouvelleListe">Créer une liste...</button>
    <div class="modal fade text-start" id="modalNouvelleListe" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Nouvelle liste</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{{ route('listes.store') }}">
                    @csrf
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="recipient-name" class="col-form-label">Nom de la liste :</label>
                            <input type="text" name="nomListe" class="form-control">
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" name="listePublique" value="1" type="checkbox" id="flexSwitchCheckDefault">
                            <label class="form-check-label" for="flexSwitchCheckDefault">Liste publique</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Créer</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <!-- Importer une liste XML -->
    <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalImporterListe">Importer une liste...</button>
    <div class="modal fade text-start" id="modalImporterListe" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Importer une liste</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="card bg-light m-3">
                    <div class="card-body">
                        <p>Utilisez ce template pour créer vos fichiers.</p>
                        <code><pre>&lt;&excl;--&quest;xml version&equals;&quot;1&period;0&quot; &quest;--&gt;
&lt;data&gt;
    &lt;liste&gt;Liste XML Template&lt;&sol;liste&gt;
    &lt;items&gt;
        &lt;item qte&equals;&quot;10&quot;&gt;Item 1&lt;&sol;item&gt;
        &lt;item qte&equals;&quot;20&quot;&gt;Item 2&lt;&sol;item&gt;
        &lt;item qte&equals;&quot;30&quot;&gt;Item 3&lt;&sol;item&gt;
    &lt;&sol;items&gt;
&lt;&sol;data&gt;</pre></code>
                    </div>
                </div>
                <form method="post" enctype="multipart/form-data" action="{{ route('listes.import') }}">
                    @csrf
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="recipient-name" class="col-form-label">Fichier XML à importer :</label>
                            <input type="file"  name="fichierXML" class="form-control">
                        </div>
{{--                        <div class="form-check form-switch">--}}
{{--                            <input class="form-check-input" name="listePublique" value="1" type="checkbox" id="flexSwitchCheckDefault">--}}
{{--                            <label class="form-check-label" for="flexSwitchCheckDefault">Liste publique</label>--}}
{{--                        </div>--}}
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Importer</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('contenu')
    <table class="table table-hover align-baseline">
        <colgroup>
            <col style="width: 150px" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Nom de la liste</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        @foreach($listes as $liste)
            <tr>
                <th>{{ $liste->public ? 'Liste publique' : '' }}</th>
                <td>{!! $liste->nom !!}</td>
                <td>
                    <!-- Voir la liste -->
                    <a href="{{ route('listes.show', $liste->id) }}" class="btn btn-secondary"><span class="material-icons">visibility</span></a>

                    <!-- Supprimer la liste -->
                    @if ($liste->user->id == Auth::user()->id)
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal-delete-{{ $liste->id }}">
                        <span class="material-icons">delete</span>
                    </button>
                    <div class="modal fade" id="modal-delete-{{ $liste->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal-delete-{{ $liste->id }}Label" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modal-delete-{{ $liste->id }}Label">Liste {{ $liste->nom }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Êtes-vous certain de vouloir supprimer la liste ?
                                </div>
                                <div class="modal-footer">
                                    <form class="d-inline" method="post" action="{{ route('listes.destroy', $liste->id) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger">Supprimer</button>
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

app/resources/views/listes/show.blade.php
@extends('layouts.base')

@section('titre')
    {{ $liste->nom }}
@endsection

@section('contenu')
    <table class="table table-hover align-baseline">
        <thead>
        <tr>
            <th scope="col">Nom</th>
            <th scope="col">Quantité</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach($items as $item)
            <tr>
                <th>{{ $item->nom }}</th>
                <td>{{ $item->quantite }}</td>
                <td>
                    <!-- Supprimer la liste -->
                    @if ($liste->user->id == Auth::user()->id)
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal-delete-{{ $item->id }}">
                            <span class="material-icons">delete</span>
                        </button>
                        <div class="modal fade" id="modal-delete-{{ $item->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modal-delete-{{ $item->id }}Label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="modal-delete-{{ $item->id }}Label">Liste {{ $item->nom }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Êtes-vous certain de vouloir supprimer <strong>{{ $item->nom }} ?</strong>
                                    </div>
                                    <div class="modal-footer">
                                        <form class="d-inline" method="post" action="{{ route('items.destroy', $item->id) }}">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger">Supprimer</button>
                                        </form>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection