app/routes/web.php
<?php

use App\Http\Controllers\ListesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/home', function() {
    return view('home');
})->middleware(['auth'])->name('home');

Route::resource('/listes', ListesController::class)
    ->middleware(['auth']);
Route::post('/listes/import', [ListesController::class, 'import'])
    ->name('listes.import')
    ->middleware(['auth']);

Route::get('/admin', [\App\Http\Controllers\AdminController::class, 'index'])
    ->name('admin.index')
    ->middleware(['auth']);
Route::post('/admin', [\App\Http\Controllers\AdminController::class, 'store'])
    ->name('admin.store')
    ->middleware(['auth']);

Route::resource('/search', \App\Http\Controllers\SearchController::class)
    ->middleware(['auth']);

Route::resource('/items', \App\Http\Controllers\ItemsController::class)
    ->middleware(['auth']);

app/app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SearchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // Trouver les éléments
        if ($request->has('recherche')) {
            $listes = DB::table('listes')
                ->select('id', 'liste as type', 'nom as liste', 'nom')
                ->where('nom', 'like', DB::raw('"%' . $request->recherche . '%"'))
                ->where(function($query) {
                    $query->where('user_id', '=', auth()->user()->id)
                        ->orWhere('public', '=', 1);
                })
                ->get();

            $items = DB::table('items')
                ->select('listes.id as id', 'item as type', 'listes.nom as liste', 'items.nom')
                ->join('listes', 'listes.id', '=', 'items.liste_id')
                ->where('items.nom', 'like', DB::raw('"%' . $request->recherche . '%"'))
                ->where(function($query) {
                    $query->where('user_id', '=', auth()->user()->id)
                        ->orWhere('public', '=', 1);
                })
                ->get();

            $resultats = $listes->union($items);
            \Debugbar::info($resultats);

            return view('search.index', [
                'resultats' => $resultats
            ]);
        } else {
            // Afficher le formulaire de recherche
            return view('search.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/resources/views/search/index.blade.php
@extends('layouts.base')

@section('titre')
    Rechercher
@endsection

@section('actions')
@endsection

@section('contenu')
    <div class="row">
        <form method="get">
            <div class="form-group">
                <label for="recherche">Entrez un terme afin de trouver des listes et des items</label>
                <input type="text" class="form-control" id="recherche" name="recherche" aria-describedby="recherche">
            </div>
            <div class="my-2">
                <button type="submit" class="btn btn-primary">Recherche</button>
            </div>
        </form>
    </div>

    <!-- Résultat de la recherche -->
    @isset($resultats)
        <hr>

        <h2>Résultat de recherche</h2>
        <h3 class="text-muted">{!! Request::get('recherche') !!}</h3>

        <table class="table table-hover align-baseline">
            <colgroup>
                <col style="width: 150px" />
            </colgroup>
            <thead>
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Liste</th>
                <th scope="col">Nom</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            @foreach($resultats as $row)
                <tr>
                    <td>{{ $row->type }}</td>
                    <td>{{ $row->liste }}</td>
                    <td>{{ $row->nom }}</td>
                    <td>
                        <!-- Voir la liste -->
                        <a href="{{ route('listes.show', $row->id) }}" class="btn btn-secondary"><span class="material-icons">visibility</span></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endisset
@endsection